name: Node.js Package

on:
  push:
    branches:
      - dev

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.0.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'New Version of alloy-icons released.\nsee: https://yottaltd.github.io/alloy-icons/'
